version: "3.8"

services:
  node-app:
    build: Sample-Node-App/.
    container_name: node-app
    ports:
      - "9000:9000"
    networks:
      - prom
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prom-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - prom
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - prom
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - prom

volumes:
  grafana-storage:

networks:
  prom:
    driver: bridge
